# Generated by Django 5.1.6 on 2025-02-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
